config/routes.rb
Rails.application.routes.draw do
  resources :topics, only: [:index, :show]

  resources :comments
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  resources :portfolios, except: [:show] do
    put :sort, on: :collection
  end
  get 'portfolio/angular', to: 'portfolios#angular', as: 'portfolio_angular'
  get 'portfolio/ruby', to: 'portfolios#ruby_on_rails', as: 'portfolio_ruby_on_rails'
  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'

  get 'slcc-news', to: 'pages#slcc_news'
  get 'about-me', to: 'pages#about'
  get 'contact', to: 'pages#contact'

  resources :blogs do
    member do
      get :toggle_status
    end
  end

  mount ActionCable.server => '/cable'

  root to: 'pages#home'
end

app/views/shared/_application_footer.html.erb
<section class="block app-block-footer mastfoot">
      <div class="container">
        <div class="row">
          <div class="col-sm-2 mb-4">
            <ul class="list-unstyled list-spaced">
              <li><h6 class="text-uppercase">Products</h6></li>
              <li>Todo</li>
              <li>Calendario</li>
              <li>Email Town</li>
              <li>Pomodorotary</li>
              <li>ChillTower</li>
            </ul>
          </div>
          <div class="col-sm-2 mb-4">
            <ul class="list-unstyled list-spaced">
              <li><h6 class="text-uppercase">Extras</h6></li>
              <li>AutotuneU</li>
              <li>Freestyler</li>
              <li>Chillaxation</li>
            </ul>
          </div>
          <div class="col-sm-2 mb-4">
            <ul class="list-unstyled list-spaced">
              <li><h6 class="text-uppercase">Support</h6></li>
              <li>Online Support</li>
              <li>Telephone Sales</li>
              <li>Help Desk</li>
              <li>Workshops</li>
            </ul>
          </div>
          <div class="col-sm-6">
            <h6 class="text-uppercase">About</h6>
            <p>Shoutout to Invision team for creating the <a href="http://www.invisionapp.com/do">Do UI kit</a> that we used to fake our app screenshots. Also to the Dribbble community for providing phone mockups that look amazing.</p>
          </div>
        </div>
      </div>
      <div class="row">
        <p class="col-sm-12 center"><%= copyright_generator %></p>
      </div>
    </section>

app/views/shared/_application_nav.html.erb
<div class="container pt-4 card">
  <nav class="navbar navbar-light navbar-toggleable-sm navbar-static-top text-uppercase app-navbar mb-4">
    <button
      class="navbar-toggler navbar-toggler-right hidden-md-up"
      type="button"
      data-toggle="collapse"
      data-target="#navbarResponsive"
      aria-controls="navbarResponsive"
      aria-expanded="false"
      aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <a class="navbar-brand mr-auto" href="../">
      <span>Ben Whipple</span>
    </a>

    <div class="collapse navbar-collapse" id="navbarResponsive">
      <ul class="nav navbar-nav ml-auto">
        <li class="nav-item ">
          <%= nav_helper 'nav-link', 'li' %>
          <%= login_helper 'nav-link' %>
        </li>
      </ul>
    </div><!--/.nav-collapse -->
  </nav>
</div>

app/views/shared/_blog_footer.html.erb
<footer class="blog-footer">
  <p>
  <%= copyright_generator %>
  </p>

  <p>
    <a href="#">Back to top</a>
  </p>
</footer>

app/views/shared/_blog_masthead.html.erb
<div class="blog-header">
  <div class="container">
    <h1 class="blog-title">The Bootstrap Blog</h1>
    <p class="lead blog-description">An example blog template built with Bootstrap.</p>
    <span>
      <%= link_to 'Write a New Blog |', new_blog_path if logged_in?(:site_admin) %>
    </span>
    <span>
      <%= link_to 'Topics', topics_path %>
    </span>
  </div>
</div>

app/views/shared/_blog_nav.html.erb
<nav class="navbar navbar-toggleable-md navbar-light bg-faded blog-nav">
  <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
   <span class="navbar-toggler-icon"></span>
 </button>

 <div class="container">
  <%= link_to "Ben Whipple", root_path, class: 'navbar-brand' %>

   <div class="collapse navbar-collapse" id="navbarSupportedContent">
     <ul class="navbar-nav mr-auto">
       <%= nav_helper 'nav-link', 'li' %>
       <%= login_helper 'nav-link' %>
     </ul>
   </div>
 </div>
</nav>

<div class="blog-masthead">
  <div class="container">
    <nav class="nav blog-nav">
      <%= nav_helper 'nav-link', 'span' %>
      <%= login_helper 'nav-link' %>
    </nav>
  </div>
</div>

app/views/shared/_blog_sidebar.html.erb
<div class="col-sm-3 offset-sm-1 blog-sidebar">
  <div class="sidebar-module sidebar-module-inset">
    <h4>About</h4>
    <p>Etiam porta <em>sem malesuada magna</em> mollis euismod. Cras mattis consectetur purus sit amet fermentum. Aenean lacinia bibendum nulla sed consectetur.</p>
  </div>

    <%= source_helper("alert alert-info blog-sidebar-source") %>


  <div class="sidebar-module">
    <h4>Elements Used</h4>
    <ol class="list-unstyled">
      <li><a href="#">Hydrogen</a></li>
      <li><a href="#">Helium</a></li>
      <li><a href="#">Lithium</a></li>
      <li><a href="#">Beryllium</a></li>
      <li><a href="#">Boron</a></li>
      <li><a href="#">Carbon</a></li>
      <li><a href="#">Nitrogen</a></li>
      <li><a href="#">Oxygen</a></li>
      <li><a href="#">Fluorine</a></li>
      <li><a href="#">Neon</a></li>
      <li><a href="#">Sodium</a></li>
      <li><a href="#">Magnesium</a></li>
    </ol>
  </div>

  <div class="sidebar-module">
    <h4>Topics</h4>
    <% @sidebar_topics.each do |topic| %>
      <p><%= link_to topic.title, topic_path(topic) %></p>
    <% end %>
  </div>


  <div class="sidebar-module">
    <h4>Elsewhere</h4>
    <ol class="list-unstyled social-links">
       <li><a href="#"><%= fa_icon "github" %></a></li>
       <li><a href="#"><%= fa_icon "instagram" %></a></li>
       <li><a href="#"><%= fa_icon "facebook" %></a></li>
       <li><a href="#"><%= fa_icon "twitter" %></a></li>
    </ol>
  </div>
</div>

app/views/shared/_nav.html.erb
<div class="card">
<%= link_to "Home", root_path %>
<%= link_to "About Me", about_me_path %>
<%= link_to "Contact", contact_path %>
<%= link_to "Portfolios", portfolios_path %>
<%= link_to "Blogs", blogs_path %>
</div>

app/views/shared/_portfolio_footer.html.erb
<footer class="text-muted">
 <div class="container">
   <p class="float-right">
     <%= link_to 'All Portfolio Items', portfolios_path %> /
     <a href="#">Back to top</a>
   </p>
  <p>
    <%= copyright_generator %>
  </p>
 </div>
</footer>

app/views/shared/_portfolio_masthead.html.erb
<section class="jumbotron text-center">
  <div class="container">
    <h1 class="jumbotron-heading">My Portfolio</h1>
    <p class="lead text-muted">Something short and leading about the collection below—its contents, the creator, etc. Make it short and sweet, but not too short so folks don't simply skip over it entirely.</p>
    <p>
      <%= link_to 'Find Out More About Me', about_me_path, class: 'btn btn-primary' %>
      <%= link_to 'My Blog', blogs_path, class: 'btn btn-secondary' %>
    </p>
  </div>
</section>

app/views/shared/_portfolio_nav.html.erb
<nav class="navbar navbar-toggleable-md navbar-light bg-faded">
  <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <a class="navbar-brand" href="#"><%= fa_icon "fa-fighter-jet" %></a>

  <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
    <ul class="navbar-nav mr-auto mt-2 mt-md-0">
      <li class="nav-item">
        <%= nav_helper 'black-text', 'li' %>
        <li><%= login_helper 'black-text' %></li>
      </li>
    </ul>
  </div>
</nav>